// Lista de libros (estática)
const libros = [
    { titulo: "El Principito", autor: "Antoine de Saint-Exupéry" },
    { titulo: "Cien Años de Soledad", autor: "Gabriel García Márquez" },
    { titulo: "1984", autor: "George Orwell" },
    { titulo: "El principito", autor: "Antoine de Saint-Exupéry" },
    { titulo: "Cien años de soledad", autor: "Gabriel García Márquez" },
    { titulo: "El Proceso", autor: "Franz Kafka" },
    { titulo: "Confesiones", autor: "San Agustin" },
    { titulo: "Ética", autor: "Benedictus de Spinoza" },
    { titulo: "El extranjero", autor: "Albert Camus" },
    { titulo: "El hombre en busca de sentido", autor: "Viktor Frankl" },
    { titulo: "De animales a dioses", autor: "Yuval Noah Harari" },
    { titulo: "El precio de la pasión", autor: "Gabriel Rolón" },
    { titulo: "El puñal", autor: "Jorge Fernandéz Díaz" },
    { titulo: "El fausto", autor: "Johann Wolfgang Von Goethe" },
    { titulo: "Como hacer que te pasen cosas buenas", autor: "Marian Rojas Estapé" },
    { titulo: "Un mundo feliz", autor: "Aldous Huxley" },
    { titulo: "Nexus", autor: "Yuval Noah Harari" },
    { titulo: "Martín Fierro", autor: "José Hernández" },
    { titulo: "Romancero gitano", autor: "Federico García Lorca" },
    { titulo: "Hamlet", autor: "William Shakspeare" },
    { titulo: "El fantasma de Canterville", autor: "Oscar Wilde" },
    { titulo: "Introducción a la historia de la Filosofía", autor: "Georg Hegel" },
    { titulo: "Las 120 jornadas de Sadoma", autor: "Marqués de Sade" },
    { titulo: "Viajes de Gulliver", autor: "Jonathan Swift" },
    { titulo: "Las 33 estrategias de la guerra", autor: "Robert Greene" },
    { titulo: "Cinco semanas en globo", autor: "Julio Verne" },
    { titulo: "El principito", autor: "Antoine de Saint-Exupéry" },
    { titulo: "El anticristo", autor: "Friedrich Nietzsche" },
    { titulo: "Ensayo sobre el libre albedrío", autor: "Arthur Schopenhauer" },
    { titulo: "Cartas de amor", autor: "Sigmund Freud" },
    { titulo: "El amor, las mujeres y la muerte", autor: "Arthur Shopenhauer" },
    { titulo: "El hombre mediocre", autor: "José Ingenieros" },
    { titulo: "Las fuerzas morales", autor: "José Ingenieros" },
    { titulo: "El origen de la tragedia", autor: "friedrich nietzsche" },
    { titulo: "Así habló Zaratustra", autor: "friedrich nietzsche" },
    { titulo: "Más allá del bien y del mal", autor: "friedrich nietzsche" },
    { titulo: "El caminante y su sombra", autor: "friedrich nietzsche" },
    { titulo: "La gaya ciencia", autor: "friedrich nietzsche" },
    { titulo: "Aurora", autor: "friedrich nietzsche" },
    { titulo: "La génesis de la moral", autor: "friedrich nietzsche" },
    { titulo: "Psicología y Pedagogía", autor: "Jean Piaget" },
    { titulo: "Henry Troyat", autor: "Fiódor Dostoievski" },
    { titulo: "Las 48 leyes del poder", autor: "Robert Greene" },
    { titulo: "El club de las 5 de la mañana", autor: "Robin Sharma" },
    { titulo: "Argentina 1910-2010", autor: "Roberto Russell" },
    { titulo: "La metamorfosis", autor: "Franz Kafka" },
    { titulo: "Poética", autor: "Aristóteles" },
    { titulo: "Antígona", autor: "Sófocles" },
    { titulo: "Diálogos", autor: "Platón" },
    { titulo: "El caballero de Harmental", autor: "Alejandro Dumas" },
    { titulo: "Discurso del método", autor: "René Descartes" },
    { titulo: "Convencer a Dios", autor: "Deepak Chopra" },
    { titulo: "El bosón de Higgs no te va a hacer la cama", autor: "Javier Santaolalla" },
    { titulo: "¿Qué hace un bosón como tú, en un big bang como?", autor: "Javier Santaolalla" },
    { titulo: "Heráclito y Pármenides", autor: "Aprende a pensar" },
    { titulo: "Séneca", autor: "Aprender a pensar" },
    { titulo: "Aristóteles", autor: "Aprender a pensar" },
    { titulo: "Epicuro", autor: "Aprender a pensar" },
    { titulo: "Arquímedes en el sitio de Siracusa", autor: "Aprender a pensar" },
    { titulo: "Los siete libros de la sabiduría", autor: "Séneca" },
    { titulo: "Carta sobre la tolerancia", autor: "John Locke" },
    { titulo: "La política", autor: "Aristóteles " },
    { titulo: "El arte de amar", autor: "Ovidio" },
    { titulo: "La divina comedia", autor: "Dante Alighieri" },
    { titulo: "Metafísica", autor: "Aristóteles" },
    { titulo: "La República", autor: "Platón" },

    { titulo: "Principios elementales de la Filosofía", autor: "Georges Politzer" },
    { titulo: "La Odisea", autor: "Homero" },
    { titulo: "La eneida", autor: "Virgilio" },
    { titulo: "La ilíada", autor: "Homero" },
    { titulo: "20 poemas de amor", autor: "Pablo Neruda" },
    { titulo: "Las venas abiertas de América Latina", autor: "Eduardo Galeano" },
    { titulo: "Historias del cerebro", autor: "Alejandra Folgaroit, Marcelo Merello" },
    { titulo: "Jorge Boccanera", autor: "La pasión de los poetas" },
    { titulo: "Yihad", autor: "Ahmed Rashid" },
    { titulo: "Pistorius", autor: "John Carlin" },
    { titulo: "El teorema de Júpiter", autor: "Elena Castillo Castro" },
    { titulo: "Padres, maestros y políticos", autor: "Pablo Da Silveira" },
    { titulo: "Mala Lerche", autor: "Ricardo Porta, Eduardo Rodríguez" },
    { titulo: "Memorias de África", autor: "Isak Dinesen" },
    { titulo: "La casa de Bernarda Alba- La zapatera prodigiosa", autor: "Federico García Lorca" },
    { titulo: "Bodas de sangre- Mariana Pineda", autor: "Federico García Lorca" },
    { titulo: "Manifiesto comunista", autor: "Karl Marx y Friedrich Engels" },
    { titulo: "El origen de las especies", autor: "Charles Darwin " },
    { titulo: "El príncipe", autor: "Nicolás Maquiavelo" },
    { titulo: "El 18 brumario de Luis Bonaparte", autor: "Karl Marx" },
    { titulo: "Psicomagia", autor: "Alejandro Jodorowsky" },
    { titulo: "Guerreros del corazón", autor: "Danaan Parry" },
    { titulo: "Arquetipos e inconsciente colectivo", autor: "Carl Gustav Jung" },
    { titulo: "El negocio del siglo 21", autor: "Robert Kiyosaki" },
    { titulo: "Todo oscuro, sin estrellas", autor: "Stephen King" },
    { titulo: "Páramo de espejos", autor: "Claudio Obregón Clairín" },
    { titulo: "El don de la vida", autor: "Fernando Vallejo" },
    { titulo: "Conocer al Diego", autor: "Daniel Arcucci" },
    { titulo: "¿Qué ves cuando te ves?", autor: " Eduardo Chaktoura, Karina Vilella" },
    { titulo: "Nosotros los cubanos", autor: "Guillermo Rodríguez Rivera" },
    { titulo: "La emancipación argentina y americana ", autor: "Félix Luna" },
    { titulo: "Los sufrimientos del joven Werther", autor: "Johann Wolfgang Goethe " },
    { titulo: "Usar el cerebro", autor: "Facundo Manes" },
    { titulo: "Argentina con pecado concebida", autor: "Federico Andahazi" },
    { titulo: "Ágilmente", autor: "Estanislao Bachrach" },
    { titulo: "Donde todo brilla", autor: "Alice Keller" },
    { titulo: "Opiniones y sentencias", autor: "Federico Nietzsche" },
    { titulo: "El duelo", autor: "Gabriel Rolón" },
    { titulo: "El retrato de Dorian Gray", autor: "Oscar Wilde" },
    { titulo: "Rayuela", autor: "Julio Cortázar" },
    { titulo: "El mundo de sofía", autor: "Jostein Gaarder" },
    { titulo: "El miedo a la libertad", autor: "Erich Fromm" },
    { titulo: "las mil y una noche", autor: "" },
    { titulo: "Crítica a la razón pura", autor: "Emmanuel Kant" },
    { titulo: "Crimen y castigo", autor: "Fedor Dostoievski" },
    { titulo: "El otoño del patriarcado", autor: "Gabriel García Márquez" },
    { titulo: "Rebelión en la granja", autor: "George Orwell" },
    { titulo: "El irak que yo vi", autor: "Elías Konsol" },
    { titulo: "El fútbol y las masas", autor: "Juan José Sebreli" },
    { titulo: "Estamos como somos", autor: "Tomás Bulat" },
    { titulo: "La economía de tu vida", autor: "Tomás Bulat" },
    { titulo: "1984", autor: "George Orwell" },
    { titulo: "Historia de dos ciudades", autor: "Charles Dickens" },
    { titulo: "Hábitos Átomicos", autor: "James Clear" },
    { titulo: "El misterio del cuarto amarillo", autor: "Gaston Leroux" },
    { titulo: "El equilibrista", autor: "Federico Andahazi" },
    { titulo: "El monje que vendió su ferrari", autor: "Robin Sharma" },
    { titulo: "Amor líquido", autor: "Zygmunt Bauman" },
    { titulo: "Memoria del fuego", autor: "Eduardo Galeano" },
    { titulo: "Don Quijote de la Mancha", autor: "Miguel de Cervantes" },
      
    
    // Agregá más libros acá
];